### ISSUE TITLE
Feature Request - явным образом прописать тип у TA DC

### ISSUE THREAD

**Issue by SychevIgor** [SEAFTeam/seaf-core#103]
https://github.com/SEAFTeam/seaf-core/blob/76cad7be87619d725dbd7a8779bb43efd7fdc4a9/entities/ta/services.yaml#L115

вот тут не понятно- это массив или строка. по смысле и тексту- массив

**Comment by SychevIgor** [comment]
Говорят, что строка

**Comment by talifan** [comment]
исправлени вот тут https://github.com/SEAFTeam/seaf-core/pull/106
