### ISSUE TITLE
Bug Report - hpa на уровне всего k8s

### ISSUE THREAD

**Issue by SychevIgor** [SEAFTeam/seaf-core#21]
https://github.com/SEAFTeam/seaf-core/blob/b4413401546411bf06440a7b57d18eeb6d2afdb7/entities/ta/services.yaml#L422

я столкнулся с проблемой описания k8s. я понимаю смысл hpa для deployment т.к. скейлится именно он. но я не понимаю, что такое hpa для всего кластера.
вот у меня пример- есть кластер, на нем живет ас и ее фп. для ас- hpa есть, для фп- нет. что мне писать на кластере (at least one?). другой пример- 2 компонента одной системы, но в разных deployment. один скейлится, второй нет через hpa - опять н понятно, что писать в hpa.

**Comment by talifan** [comment]
Исправлено в следюущем релизе.
