### ISSUE TITLE
иерархия сущностей k8s

### ISSUE THREAD

**Issue by SychevIgor** [SEAFTeam/seaf-core#22]
Сейчас, image знает - к каким containers он привязан. container знает- к каким pod он указан. pod знает, в каком он deployment. deployment знает на каком он k8s

Кажется, что ссылки должны быть в другом направлении. т.е. container знает- где его образ, deployment знает - какие у него контейнеры есть (разве что k8s знающий про свои deployment- может не очень идея).

**Comment by SychevIgor** [comment]
Возможно не в тот репозитарий написал, а надо было в https://github.com/SEAFTeam/seaf-dzo-core но с другой стороны- саму сущности k8s скорее должны быть в core, чем в core-dzo

**Comment by talifan** [comment]
В трёх репах внёс изменения https://github.com/SEAFTeam/seaf-dzo-example/pull/37
