### ISSUE TITLE
Semantic versioning. To be, or not to be

### ISSUE THREAD

**Issue by SychevIgor** [SEAFTeam/seaf-core#28]
Возник концептуальный вопрос- поддерживается ли в этой репе semantic versioning? 

между версией 1.2.3 и 1.2.4 (по идеи, обратной совместимости это не должно ломать) были удалены 2 сущности от kadzo
https://github.com/SEAFTeam/seaf-core/commit/c20b94498ff42dd6bce08b08ef21c65d06625591
https://semver.org/lang/ru/ если верить описанию, то получается - что удаление сущностей, которые раньше были- это точно не patch

**Comment by kmyachin** [comment]
Сами сущности просто переедут в расширение seaf-dzo-core.
Насчет семантического версионирования - соглашусь. Давай сейчас спишем на то, что в силу разделения одного репозитория (в котором ранее велась разработка) на несколько, остался ряд артефактов, которые на данный момент допричесываются между ними.
