### ISSUE TITLE
Feature Request - обновить документацию

### ISSUE THREAD

**Issue by SychevIgor** [SEAFTeam/seaf-core#36]
На пример- надо переместить readme тех архитектуры в docs
![image](https://github.com/SEAFTeam/seaf-core/assets/578954/10fbab45-d7bb-468c-98b1-d6a3ca0d0244)

**Comment by SychevIgor** [comment]
Переименовать в этом readme файле название пакета Reverse в IaaS т.к. пакет называется именно так.

**Comment by SychevIgor** [comment]
было бы правильно обновить документацию в часть k8s. сейчас в entities описывается только k8s, а в документации еще что-то про openshift, но в entities нет ни каких types, чтобы был open shift описан

![image](https://github.com/SEAFTeam/seaf-core/assets/578954/fea2bc9f-5acb-4bdf-8317-2c68ab02f44e)

**Comment by SychevIgor** [comment]
было бы правильно-  в документации к тех архитектуре сопоставить title из entities и то, что написано в документации (хотя бы в скобочках написать английскую версию)

пример- понять, что network_links - это канал передачи данных, по простому не получится. надо думать (думать- это хорошо, а консистентный naming еще лучше)

другой пример "объектная схд". Мне понадобилось время, чтобы догадаться, что это "Simple Storage Service"

![image](https://github.com/SEAFTeam/seaf-core/assets/578954/9f129c42-69b1-44f7-8759-19d226b57a3d)

**Comment by SychevIgor** [comment]
Хочется еще и структуру каталогов поправить.
reverse - не обязателен, если мы iaas не используем- а на схеме он есть.
с другой стороны- не указаны папки menu/functions (раз уж показываем структуру- давайте ее показывать... хотя и не понятно зачем)
![image](https://github.com/SEAFTeam/seaf-core/assets/578954/655b7bcc-61c0-4785-8c14-4fce84d754e1)

**Comment by talifan** [comment]
Исправлена документация по ТА в будущем коммите.
