### ISSUE TITLE
Bug Report - в сущности сервисе backup поле расписание стоит переработать 

### ISSUE THREAD

**Issue by SychevIgor** [SEAFTeam/seaf-core#47]
Сервис бекапа не должен содержать поле schedule строкового т.к. один и тот-же сервис может предоставлять разную гранулярность бэкапирования. для системы 1- ежедневно, для системы 2 -каждое утро в 8 утра. для системы 3 - каждый четверг и т.п. и это все один сервис, реализуемый одной системой (АС). 

В итоге, это поля для нас достаточно бессмысленно к заполнению. а создавать по сервису на каждый тип расписания - кажется странной идеей

![image](https://github.com/SEAFTeam/seaf-core/assets/578954/564ba140-50fa-42c0-9958-30a4aebdac9f)

**Comment by talifan** [comment]
Будет удалено в будущем релизе.
