### ISSUE TITLE
Bug Report - карточки в Тех Архитектуре не отображают название половины полей

### ISSUE THREAD

**Issue by SychevIgor** [SEAFTeam/seaf-core#48]
При попытке посмотреть карточки техсервисов в example, обнаружил ошибку- что очень многие карточки не содержат тайтлов обьектов. такое ощущение, что _metamodel_\seaf-core\entities\ta\presentation\ta.yaml есть какая-то ошибка

корректно отображается только карточки - хардверных хранилищ, серверов, сетевых устройств, кластеров, k8s кластеров, network links, мониторинг и хранилища. но более половины карточек не содержат части названий полей

Может это проблемы к example, но вы уже сами внутри заведите- если не в том месте

![image](https://github.com/SEAFTeam/seaf-core/assets/578954/48a9ae36-c735-4248-880b-6fd8ce245de8)
![image](https://github.com/SEAFTeam/seaf-core/assets/578954/882aa50f-affa-4b65-9795-43fa585dd054)

**Comment by koa73** [comment]
исправил в релизе 1.28

**Comment by talifan** [comment]
Закрыто
