### ISSUE TITLE
Feature Request - Тех Архитектура Лицензии

### ISSUE THREAD

**Issue by SychevIgor** [SEAFTeam/seaf-core#49]
Кажется, что сущности seaf.ta.services.software и фичи вокруг нее нуждаются в улучшениях.

1- Хочется получить какой-то базовый набор валидаторов к этой сущности (не только список required полей). Для этого, наверное надо уйти от strings полей и перейти к чему-то более структурированному.
2- Как предполагается отображать лицензию без ограничения количества? сейчас lic_qty типа integer. Указывать -1 или бесконечно большое значение? (это интересно, есть появятся все таки валидаторы)
3- что делать, если лицензий не  серверная? лицензия на условную среду разработки- она с серверами линкуется, а с рабочими станциями. Рабочие станции в seaf не ведутся (да и сервера - тоже спорный вопрос). В итоге -сущности выглядит так, как будто мы должны только серверный лицензии описывать
4 - возможно стоит добавить поле- число использованных лицензий. тогда хоть какой-то полезный валидатор можно написать.

5 - возможно, стоит добавить ссылку на component/service (АС-ФП или их часть). Часто лицензии покупаются не на всю компанию, а под какие-то конкретные системы. Кроме того, хочется лицензию на базу данных слинковать как-то с компонентом базы данных конкретной системы. 
6- можно добавить ссылку на - есть ли система в РРПО

В текущем виде entity software - кажется не покрывающий базовые сценарии и польза от заведения этих данных в seaf- вызывает вопросы.

**Comment by talifan** [comment]
1. В Core останется пока так.
2. решения нет. Думаю, что можно выбирать большое число.
3. Рабочие станции ведутся через клиентские устройства - можно добавить связь.
4. Надо подумать. Пока отложим.
5. Ссылка эта есть по умолчанию у всех техсервисов.
6. Надо будет использовать расширение новое для описания лицензий.

**Comment by SychevIgor** [comment]
я этот запрос добавил еще до появления пакета https://github.com/SEAFTeam/software-registry
