### ISSUE TITLE
иерархия сущностей k8s часть 2

### ISSUE THREAD

**Issue by SychevIgor** [SEAFTeam/seaf-core#50]
В продолжении вопроса https://github.com/SEAFTeam/seaf-core/issues/22

После того, как иерархия была переработано- стало логичнее, но пару моментов осталось.

1- сейчас, deployment и statefulset знает на каком k8s они хостится. Здравый смысл подсказывает, что наверное все таки k8s знает, что на нем хостят. 

![image](https://github.com/SEAFTeam/seaf-core/assets/578954/5c720263-fa8b-41c6-a98c-915b9e36494d)
2- сейчас, deployment и statefulset знает в каком они availabilityzone_id. Если сделать ссылку из k8s на deployment/statefulset, то можно будет убрать avzon из deployment т.к. это излишняя связь.
![image](https://github.com/SEAFTeam/seaf-core/assets/578954/ec6da9c7-c842-4255-888f-b65c074ed4c2)

3 - наверное стоит сделать ссылку из компонента системы (ас) на k8s_deployment. сейчас у нас сущность deployment вообще не связано с составом АС. Сейчас у прикладного компонента нет ни каких связей с k8s - что разрывает app слой и тех слой
![image](https://github.com/SEAFTeam/seaf-core/assets/578954/564643bd-d389-4f47-871d-e804687e28ef)

**Comment by talifan** [comment]
1. Деплоймент может быть залит на разные кластера. В свойствах стоит array. Кластер, конечно, знает кто на нём хостится.
2. В теории можно убрать эту связь т.к. стоит связь с кластером, а тот в свою очередь имеет инфу о зонах доступности. Но тут скорее целевое описание деплоймента важнее - указать в каких AZ он работает. Добавил массив для этого поля.
3. Эта ссылка не предусмотрена логикой SEAF. Техслой ссылается на прикладной, а не наоборот. Ссылка из ТА в ПА имеется.
