### ISSUE TITLE
Bug Report - не корректный комментарий к полю hw_storage_connected  (скопирован с поля выше)

### ISSUE THREAD

**Issue by SychevIgor** [SEAFTeam/seaf-core#55]
https://github.com/SEAFTeam/seaf-core/blob/7d56565c61ffafeda4e32ade57d55844b753036c/entities/ta/services.yaml#L281

**Comment by SychevIgor** [comment]
https://github.com/SEAFTeam/seaf-core/blob/7d56565c61ffafeda4e32ade57d55844b753036c/entities/ta/services.yaml#L327 а тут явно не совпадает title и поле. поля про hw, а тайтл про dc

**Comment by talifan** [comment]
В будущем релизе будет исправлено
