### ISSUE TITLE
Bug Report - в описание сущности- попал какой-то странный комментарий "Вчера"

### ISSUE THREAD

**Issue by SychevIgor** [SEAFTeam/seaf-core#56]
https://github.com/SEAFTeam/seaf-core/blob/7d56565c61ffafeda4e32ade57d55844b753036c/entities/ta/services.yaml#L209

![image](https://github.com/SEAFTeam/seaf-core/assets/578954/fafdbd34-a5c9-4f7a-8f84-c8b82b585efa)

**Comment by talifan** [comment]
Исправлено
