### ISSUE TITLE
Bug Report - на метамодели не отображаются связи, которые пришли через seaf.ta.services.base.entity

### ISSUE THREAD

**Issue by SychevIgor** [SEAFTeam/seaf-core#57]
В seaf.ta.services.base.entity есть связи и на компоненты и на требований и на интеграции.
но ни одна из них не видна на метамодели. 
Понятно, что есть проблема с отображением массивов, над которой сейчас работают тут https://github.com/SEAFTeam/iaas/issues/50 и тут https://github.com/SEAFTeam/seaf-dzo-core/issues/43 но решил еще и про потерю связей при наследовании показать

**Comment by SychevIgor** [comment]
пример- мониторинг сервис типа не с чем не связан согласно схеме
![image](https://github.com/SEAFTeam/seaf-core/assets/578954/5f7b8b32-a486-463f-acbc-095cd00b5ec8)
но на самом деле связан
![image](https://github.com/SEAFTeam/seaf-core/assets/578954/df601f9d-cedb-4e36-a907-e1419dc7b8e5)

при этом - не отображаются еще и ссылка на dc_az и сервера. 
![image](https://github.com/SEAFTeam/seaf-core/assets/578954/da91ae32-d3b0-4818-9bb6-33d62c917b7b)

**Comment by talifan** [comment]
Исправление в мастере https://github.com/SEAFTeam/mm-discovery/commit/9ac9915e624146fcdfd5e79da5d72af631b7376c
