### ISSUE TITLE
Feature Request - разные типы мониторинга в одном сервисе мониторинга enum array

### ISSUE THREAD

**Issue by SychevIgor** [SEAFTeam/seaf-core#58]
Сейчас - у monitoring есть enum с типом.
Мы маленькая компания, у которой инфра и апп мониторинг вместе живут. сейчас- не совсем понятно, что нам делать? толи заводить дополнительный псеводсервис мониторинга, толи пытаться создать 2 сущности с одним monitoring_id толи просить- переделать enum в массив enum

**Comment by talifan** [comment]
Исправлено в будущем релизе. Будет array enum
