### ISSUE TITLE
Feature Request - TA добавить для сущности seaf.ta.services.network_links ссылки на network service (сетка)

### ISSUE THREAD

**Issue by SychevIgor** [SEAFTeam/seaf-core#65]
"Да, то, что seaf.ta.services.network_links не имеет связи с seaf.ta.services.network это явная недоработка. Это, действительно, может быть необходимо для понимания, что эта конкретная сеть транспортная для конкретной сетевой связи."

**Comment by talifan** [comment]
![image](https://github.com/SEAFTeam/seaf-core/assets/125357303/374c7680-fdaa-4ba1-8569-70337f53d8b3)
