### ISSUE TITLE
выпущена версия 1.2.2 без изменения версии в файле dochub.yaml 1.2.1

### ISSUE THREAD

**Issue by SychevIgor** [SEAFTeam/seaf-core#7]
давайте будем править версию в dochub.yaml при выкатке релиза

![image](https://github.com/SEAFTeam/seaf-core/assets/578954/a742e3c9-0c87-40bf-85d9-7d87b385aa1c)
![image](https://github.com/SEAFTeam/seaf-core/assets/578954/72e7fc7f-183c-4ed7-903f-e6d26f0e8f4d)

**Comment by kmyachin** [comment]
Учтем в след релизах.
